DROP DATABASE LinkKeeperDB;
CREATE DATABASE LinkKeeperDB;
USE LinkKeeperDB;

CREATE TABLE Users (
	Name VARCHAR(10) NOT NULL,
	Email VARCHAR(70) NOT NULL,
	Pass VARCHAR(40) NOT NULL,
	PRIMARY KEY (Email)
);

CREATE TABLE Categories (
	IDCategory MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
	Owner VARCHAR(50) NOT NULL,
	CATName VARCHAR(25) NOT NULL,
	FOREIGN KEY (Owner) REFERENCES Users(Email) ON UPDATE NO ACTION ON DELETE NO ACTION,
	PRIMARY KEY (IDCategory)
);

CREATE TABLE Links (
	IDCategory MEDIUMINT UNSIGNED NOT NULL,
	LinkName VARCHAR(20) NOT NULL,
	URL VARCHAR(100) NOT NULL,
	FOREIGN KEY(IDCategory) REFERENCES Categories(IDCategory) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE Logs (
	idConnection MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
	Email VARCHAR(70),
	Time datetime,
	PRIMARY KEY(idConnection)
);
INSERT INTO Users (Name,Email,Pass) VALUES ('Hugo','hugo.moragues@gmail.com',SHA1('1234'));